site_name: My Docs
theme:
  name: 'material'

  palette:
    primary: 'indigo'
    accent: 'indigo'
  
  feature:
    tabs: true

  language: 'zh'

repo_name: 'Africar-Lee/MLtest'
repo_url: 'https://africar-lee.github.io/MLtest/'

copyright: "Copyright &copy; 2022 - 2023 Africar Li"

extra:
  social:
    - type: github
      link: https://github.com/Africar-Lee

  search:
    language: 'en'

  disqus: 'AfricarL'

markdown_extensions:
  - admonition                                      # 注解块支持
  - pymdownx.arithmatex                             # 数学公式的TeX语法支持
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:                                 # 表情支持
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:                              # 任务清单支持
      custom_checkbox: true
  - pymdownx.tilde
  - meta                                            # 元数据支持

plugins:
  - search